export const transactions = [
  {
    id: 1,
    type: "Payment",
    company: "Apple",
    name: "Ivan",
    amount: 100,
    description: "Bank Of America",
    sender: "Ivan",
    date: "06-08-2023",
    percent: 3,
    status: "Pending",
    authorizedUser: "Ivan",
  },
  {
    id: 2,
    company: "Apple",
    type: "Credit",
    name: "Ivan",
    amount: 100,
    description: "Bank Of America",
    sender: "Ivan",
    date: "06-07-2022",
    percent: 3,
    status: "Approved",
  },
  {
    id: 3,
    type: "Credit",
    company: "Apple",
    name: "Ivan",
    amount: 100,
    description: "Bank Of America",
    sender: "Ivan",
    date: "06-07-2022",
    percent: 3,
    status: "Approved",
  },
  {
    id: 4,
    type: "Credit",
    company: "Apple",
    name: "Ivan",
    amount: 100,
    description: "Bank Of America",
    sender: "Ivan",
    date: "06-07-2022",
    percent: 3,
    status: "Approved",
  },
  {
    id: 5,
    type: "Credit",
    company: "Apple",
    name: "Ivan",
    amount: 100,
    description: "Bank Of America",
    sender: "Ivan",
    date: "06-07-2022",
    percent: 3,
    status: "Approved",
  },
  {
    id: 6,
    type: "Payment",
    company: "Apple",
    name: "Ivan",
    amount: 100,
    description: "Bank Of America",
    sender: "Ivan",
    date: "06-07-2022",
    percent: 3,
    status: "Approved",
  },
  {
    id: 7,
    type: "Payment",
    company: "Apple",
    name: "Ivan",
    amount: 100,
    description: "Bank Of America",
    sender: "Ivan",
    date: "06-07-2022",
    percent: 3,
    status: "Approved",
  },
  {
    id: 8,
    type: "Payment",
    company: "Apple",
    name: "Ivan",
    amount: 100,
    description: "Bank Of America",
    sender: "Ivan",
    date: "06-07-2022",
    percent: 3,
    status: "Approved",
    authorizedUser: "Ivan",
  },
  {
    id: 9,
    type: "Payment",
    company: "Apple",
    name: "Ivan",
    amount: 100,
    description: "Bank Of America",
    sender: "Ivan",
    date: "06-07-2022",
    percent: 3,
    status: "Approved",
    authorizedUser: "Ivan",
  },
  {
    id: 10,
    type: "Payment",
    company: "Apple",
    name: "Ivan",
    amount: 100,
    description: "Bank Of America",
    sender: "Ivan",
    date: "06-07-2022",
    percent: 3,
    status: "Approved",
  },
  {
    id: 11,
    type: "Payment",
    company: "Apple",
    name: "Ivan",
    amount: 100,
    description: "Bank Of America",
    sender: "Ivan",
    date: "06-07-2022",
    percent: 3,
    status: "Approved",
  },
  {
    id: 12,
    type: "Payment",
    company: "Apple",
    name: "Ivan",
    amount: 100,
    description: "Bank Of America",
    sender: "Ivan",
    date: "06-07-2022",
    percent: 3,
    status: "Approved",
  },
  {
    id: 13,
    type: "Payment",
    company: "Apple",
    name: "Ivan",
    amount: 100,
    description: "Bank Of America",
    sender: "Ivan",
    date: "06-07-2022",
    percent: 3,
    status: "Approved",
  },
];
